/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <LCD.h>
#include <UART.h>
#include <rx_int.h>
#include <tx_int.h>
#include <TX_aliases.h>
#include <TX.h>
#include <VDAC8_REF.h>
#include <PGA_GAIN.h>
#include <PGA_REF.h>
#include <IDAC8_REF.h>
#include <ADC_SAR_1.h>
#include <TOP_MUX_2.h>
#include <TOP_MUX_3.h>
#include <TOP_MUX_1.h>
#include <TOP_MUX_4.h>
#include <BOTTOM_MUX_1.h>
#include <BOTTOM_MUX_2.h>
#include <BOTTOM_MUX_3.h>
#include <BOTTOM_MUX_4.h>
#include <TOP_1_aliases.h>
#include <TOP_1.h>
#include <TOP_2_aliases.h>
#include <TOP_2.h>
#include <TOP_3_aliases.h>
#include <TOP_3.h>
#include <TOP_4_aliases.h>
#include <TOP_4.h>
#include <BOTTOM_1_aliases.h>
#include <BOTTOM_1.h>
#include <BOTTOM_2_aliases.h>
#include <BOTTOM_2.h>
#include <BOTTOM_3_aliases.h>
#include <BOTTOM_3.h>
#include <BOTTOM_4_aliases.h>
#include <BOTTOM_4.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <ADC_SAR_1_theACLK.h>
#include <ADC_SAR_1_Bypass_aliases.h>
#include <ADC_SAR_1_Bypass.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
